spring.application.name=eventease

# MongoDB
spring.data.mongodb.uri=mongodb+srv://eventease_admin:BmH7vupXsvEwtqMO@cluster2.rkbtbqx.mongodb.net/eventease_db?retryWrites=true&w=majority&appName=Cluster2

# Server
# server.port=8080
server.port=${PORT:8080}

# JWT
app.jwt.secret=eventeaseSecretKeyEventEaseSecretKey1280
app.jwt.expiration=86400000

# Cloudinary
cloudinary.cloud-name=dpic4mhbz
cloudinary.api-key=655828519621982
cloudinary.api-secret=dpXrZoFfFnRd3C3TUCM0qppSedE

# Logging
logging.level.org.springframework.security=DEBUG

# Swagger
swagger-url=https://eventease-20lv.onrender.com/swagger-ui/index.html
